---
title: Wanasacafe
timezone: UTC
collections:
  sections:
    title: Home
    output: false
    test: value
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
