---
title: Wanasa Kitchen
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sections
  values:
    tagline: ''
    box_body: ''
    images: []
url: https://wanasacafe.co.uk
Instagram: wanasakitchen
Menus:
- title: All Day Breakfast
  file: "/uploads/wanasa-breakfast-menu-9e8af6.pdf"
- title: All Day Brunch
  file: "/uploads/wanasa-lunch-menu-b05b5f.pdf"
- title: For Kids
  file: "/uploads/wanasa-kids-menu-f1b91c.pdf"
- title: Drinks
  file: "/uploads/wanasa-drinks-menu-0c4a59.pdf"
- title: Teas
  file: "/uploads/wanasa-tea-menu-e8e544.pdf"
