---
title: Wanasa Kitchen
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sections
  values:
    tagline: ''
    box_body: ''
    images: []
url: https://wanasacafe.co.uk
Instagram: wanasakitchen
Menus:
- title: Breakfast & Brunch
  file: "/uploads/wanasa-lunch-menu-85d4f4.pdf"
- title: For Kids
  file: "/uploads/wanasa-kids-menu-7ecb29.pdf"
- title: Drinks
  file: "/uploads/wanasa-drinks-menu-e5e6a8.pdf"
- title: Teas
  file: "/uploads/wanasa-tea-menu-b70694.pdf"
