---
title: Wanasa Kitchen
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sections
  values:
    tagline: ''
    box_body: ''
    images: []
url: https://wanasacafe.co.uk
Instagram: wanasakitchen
Menus:
- title: All Day Brunch
  file: "/uploads/wanasa-lunch-menu-a7be68.pdf"
- title: For Kids
  file: "/uploads/wanasa-kids-menu-9fce2c.pdf"
- title: Drinks
  file: "/uploads/wanasa-drinks-menu-0c7716.pdf"
- title: Teas
  file: "/uploads/wanasa-tea-menu-a47d8b.pdf"
