---
title: Wanasa Kitchen
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: sections
  values:
    tagline: ''
    box_body: ''
    images: []
url: https://wanasacafe.co.uk
Instagram: wanasakitchen
Menus:
- title: All Day Breakfast
  file: "/uploads/wanasa-breakfast-menu-0a3e88.pdf"
- title: All Day Brunch
  file: "/uploads/wanasa-lunch-menu-497e7a.pdf"
- title: For Kids
  file: "/uploads/wanasa-kids-menu.pdf"
- title: Drinks
  file: "/uploads/wanasa-drinks-menu.pdf"
- title: Teas
  file: "/uploads/wanasa-tea-menu.pdf"
